name: "SAM Deploy"
description: "Deploy SAM"
inputs:
  target-env:
    description: "Target env. dev, stage, or prod"
    required: true
  role-arn:
    description: "Role ARN used for CF"
    required: true
  environment:
    description: 'Environment to run job against'
    type: environment
    required: true
runs:
  using: "composite"
  env:
    STACK_NAME: ${{ github.event.repository.name }}-${{ inputs.environment }}
  steps:
    - name: SAM Build
      shell: bash
      run: echo ${{ env.STACK_NAME }} ${{ inputs.environment }} ${{ inputs.target-env }} ${{ inputs.role-arn }}
