name: "SAM Deploy"
description: "Deploy SAM"
inputs:
  stack-name:
    description: "CloudFormation stack name"
    required: true
  target-env:
    description: "Target env. dev, stage, or prod"
    required: true
  role-arn:
    description: "Role ARN used for CF"
    required: true
  environment:
    description: 'Environment to run job against'
    type: environment
    required: true
runs:
  using: "composite"
  steps:
    - name: SAM Build
      shell: bash
      run: echo ${{ inputs.environment }} ${{ inputs.stack-name }} ${{ inputs.target-env }} ${{ inputs.role-arn }}
