name: Master CI/CD
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/composite/sam-deploy
        with:
          stack-name: "stack-name"
          target-env: "target-env"
          role-arn: "role-arn"
          environment: dev
