name: Master CI/CD
on:
  push:
    tags:
      - v*
permissions:
  id-token: write
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: phitran/phi-test/.github/workflows/release.yml@main
