name: Master CI/CD
on:
  push:
    tags:
      - v*
permissions:
  id-token: write
  contents: read
jobs:
  test:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/composite/sam-deploy
        stack-name: "stack-name"
        target-env: "target-env"
        role-arn: "role-arn"
